from django.urls import path
from api.views import start, next_step, prev_step, goto_step, update, regenerate, render_result, upload, sessions, session_detail, trace, export_session, export_session_md, import_session, health, llm_config, decompose, decompose_trace, decompose_split, decompose_to_topics, decompose_edit, decompose_auto_split, chat, chat_answer, chat_stop, user_preferences, explain, session_delete, session_rename, app_settings

urlpatterns = [
    path("", health, name="health"),
    path("api/health", health, name="api-health"),
    path("api/start", start, name="start"),
    path("api/next", next_step, name="next"),
    path("api/prev", prev_step, name="prev"),
    path("api/goto", goto_step, name="goto"),
    path("api/explain", explain, name="explain"),
    path("api/update", update, name="update"),
    path("api/regenerate", regenerate, name="regenerate"),
    path("api/render_result", render_result, name="render-result"),
    path("api/upload", upload, name="upload"),
    path("api/chat", chat, name="chat"),
    path("api/chat_answer", chat_answer, name="chat-answer"),
    path("api/chat_stop", chat_stop, name="chat-stop"),
    path("api/user_prefs", user_preferences, name="user-prefs"),
    path("api/sessions", sessions, name="sessions"),
    path("api/sessions/<str:sid>", session_detail, name="session_detail"),
    path("api/sessions/<str:sid>/trace", trace, name="trace"),
    path("api/sessions/<str:sid>/rename", session_rename, name="session_rename"),
    path("api/sessions/<str:sid>/delete", session_delete, name="session_delete"),
    path("api/session/<str:sid>/export", export_session, name="export_session"),
    path("api/session/<str:sid>/export_md", export_session_md, name="export_session_md"),
    path("api/session/import", import_session, name="import_session"),
    path("api/llm/config", llm_config, name="llm-config"),
    path("api/settings", app_settings, name="app-settings"),
    path("api/decompose", decompose, name="decompose"),
    path("api/decompose/<str:sid>/trace", decompose_trace, name="decompose-trace"),
    path("api/decompose/<str:sid>/split", decompose_split, name="decompose-split"),
    path("api/decompose/<str:sid>/to_topics", decompose_to_topics, name="decompose-to-topics"),
    path("api/decompose/<str:sid>/edit", decompose_edit, name="decompose-edit"),
    path("api/decompose/<str:sid>/auto_split", decompose_auto_split, name="decompose-auto-split"),
]
