const { scene, BLUE, DOWN, Difference, Ellipse, Exclusion, FadeIn, GREEN, Group, Intersection, LEFT, MarkupText, ORANGE, PINK, RED, RIGHT, Scene, Text, UP, Union, YELLOW, addVec, scaleVec } = ctx;
const ellipse1 = new Ellipse({ width: 4.0, height: 5.0, fillOpacity: 0.5, color: BLUE, strokeWidth: 10 }).moveTo(LEFT);
  const ellipse2 = ellipse1.copy().setColor({ color: RED }).moveTo(RIGHT);
  const boolOpsText = new MarkupText({ text: "<u>Boolean Operation</u>" }).nextTo(ellipse1, scaleVec(3, UP));
  const ellipseGroup = new Group(boolOpsText, ellipse1, ellipse2).moveTo(scaleVec(3, LEFT));
  await scene.play(new FadeIn(ellipseGroup));
  const i = new Intersection({ arg0: ellipse1, arg1: ellipse2, color: GREEN, fillOpacity: 0.5 });
  await scene.play(i.animate.scale(0.25).moveTo(addVec(scaleVec(5, RIGHT), scaleVec(2.5, UP))));
  const intersectionText = new Text({ text: "Intersection", fontSize: 23 }).nextTo(i, UP);
  await scene.play(new FadeIn(intersectionText));
  const u = new Union({ arg0: ellipse1, arg1: ellipse2, color: ORANGE, fillOpacity: 0.5 });
  const unionText = new Text({ text: "Union", fontSize: 23 });
  await scene.play(u.animate.scale(0.3).nextTo(i, DOWN, { buff: unionText.height * 3 }));
  unionText.nextTo(u, UP);
  await scene.play(new FadeIn(unionText));
  const e = new Exclusion({ arg0: ellipse1, arg1: ellipse2, color: YELLOW, fillOpacity: 0.5 });
  const exclusionText = new Text({ text: "Exclusion", fontSize: 23 });
  await scene.play(e.animate.scale(0.3).nextTo(u, DOWN, { buff: exclusionText.height * 3.5 }));
  exclusionText.nextTo(e, UP);
  await scene.play(new FadeIn(exclusionText));
  const d = new Difference({ arg0: ellipse1, arg1: ellipse2, color: PINK, fillOpacity: 0.5 });
  const differenceText = new Text({ text: "Difference", fontSize: 23 });
  await scene.play(d.animate.scale(0.3).nextTo(u, LEFT, { buff: differenceText.height * 3.5 }));
  differenceText.nextTo(d, UP);
  await scene.play(new FadeIn(differenceText));