const { scene, Angle, LEFT, Line, MathTex, RED, RIGHT, Scene, ValueTracker } = ctx;
const rotationCenter = LEFT;
  const thetaTracker = new ValueTracker({ value: 110 });
  const line1 = new Line({ start: LEFT, end: RIGHT });
  const lineMoving = new Line({ start: LEFT, end: RIGHT });
  const lineRef = lineMoving.copy();
  lineMoving.rotate(thetaTracker.getValue() * (Math.PI / 180), { aboutPoint: rotationCenter });
  const a = new Angle({ line1: line1, line2: lineMoving, radius: 0.5, otherAngle: false });
  const tex = new MathTex({ latex: "\\theta" }).moveTo(new Angle({ line1: line1, line2: lineMoving, radius: 0.5 + (3 * SMALL_BUFF), otherAngle: false }).pointFromProportion(0.5));
  scene.add(line1, lineMoving, a, tex);
  await scene.wait(1);
  lineMoving.addUpdater((x) => x.become(lineRef.copy()).rotate(thetaTracker.getValue() * (Math.PI / 180), { aboutPoint: rotationCenter }));
  a.addUpdater((x) => x.become(new Angle({ line1: line1, line2: lineMoving, radius: 0.5, otherAngle: false })));
  tex.addUpdater((x) => x.moveTo(new Angle({ line1: line1, line2: lineMoving, radius: 0.5 + (3 * SMALL_BUFF), otherAngle: false }).pointFromProportion(0.5)));
  await scene.play(thetaTracker.animateTo(40));
  await scene.play(thetaTracker.animate.incrementValue(140));
  await scene.play(tex.animate.setColor(RED));
  await scene.play(thetaTracker.animateTo(350));