const { scene, ApplyFunction, Create, DOWN, FadeIn, FadeOut, LaggedStart, MathTex, NumberPlane, Scene, Tex, Transform, UL, UP, VGroup, Write, np } = ctx;
const title = new Tex({ latex: "This is some \\LaTeX" });
  await title.waitForRender();
  const basel = new MathTex({ latex: "\\sum_{n=1}^\\infty \\frac{1}{n^2} = \\frac{\\pi^2}{6}" });
  await basel.waitForRender();
  new VGroup(title, basel).arrange(DOWN);
  await scene.play(new Write(title), new FadeIn(basel, { shift: DOWN }));
  await scene.wait(1);
  const transformTitle = new Tex({ latex: "That was a transform" });
  await transformTitle.waitForRender();
  transformTitle.toCorner(UL);
  await scene.play(new Transform(title, transformTitle), new LaggedStart([...basel.map((obj) => new FadeOut(obj, { shift: DOWN }))]));
  await scene.wait(1);
  const grid = new NumberPlane();
  const gridTitle = new Tex({ latex: "This is a grid", fontSize: 72 });
  await gridTitle.waitForRender();
  gridTitle.moveTo(transformTitle);
  scene.add(grid, gridTitle);
  await scene.play(new FadeOut(title), new FadeIn(gridTitle, { shift: UP }), new Create(grid, { duration: 3, lagRatio: 0.1 }));
  await scene.wait(1);
  const gridTransformTitle = new Tex({ latex: "That was a non-linear function \\\\ applied to the grid" });
  await gridTransformTitle.waitForRender();
  gridTransformTitle.moveTo(gridTitle, UL);
  grid.prepareForNonlinearTransform();
  await scene.play(new ApplyFunction(grid, { func: (p) => p + np.array([np.sin(p[1]), np.sin(p[0]), 0]) }));
  await scene.wait(1);
  await scene.play(new Transform(gridTitle, gridTransformTitle));
  await scene.wait(1);