const { scene, Axes, BLUE, GREEN, Line, RED, Scene, UP, UR, VGroup, WHITE, YELLOW, np } = ctx;
const axes = new Axes({ xRange: [-10, 10.3, 1], yRange: [-1.5, 1.5, 1], xLength: 10, axisConfig: { color: GREEN }, xAxisConfig: { numbersToInclude: np.arange(-10, 10.01, 2), numbersWithElongatedTicks: np.arange(-10, 10.01, 2) }, tips: false });
  const axesLabels = axes.getAxisLabels();
  const sinGraph = axes.plot((x) => np.sin(x), { color: BLUE });
  const cosGraph = axes.plot((x) => np.cos(x), { color: RED });
  const sinLabel = axes.getGraphLabel(sinGraph, "\\sin(x)", { xVal: -10, direction: UP / 2 });
  const cosLabel = axes.getGraphLabel(cosGraph, { label: "\\cos(x)" });
  const vertLine = axes.getVerticalLine(axes.i2gp(2 * Math.PI, cosGraph), { color: YELLOW, lineFunc: Line });
  const lineLabel = axes.getGraphLabel(cosGraph, "x=2\\pi", { xVal: 2 * Math.PI, direction: UR, color: WHITE });
  const plot = new VGroup(axes, sinGraph, cosGraph, vertLine);
  const labels = new VGroup(axesLabels, sinLabel, cosLabel, lineLabel);
  scene.add(plot, labels);