// Mock 事件流 —— 模拟主agent拆解 + 子agent生成/校验的过程。
// 后端接通后,这些事件由 WebSocket 推送,结构保持一致。

export type AgentRole = "user" | "orchestrator" | "animator" | "verifier" | "narrator";

export type ChatEvent =
  | { kind: "message"; role: AgentRole; text: string }
  | { kind: "plan"; title: string; stepCount: number; stepTitles: string[] }
  | { kind: "step-start"; stepId: number; title: string }
  | { kind: "code-gen"; stepId: number; code: string }
  | { kind: "verify"; stepId: number; passed: boolean; error?: string }
  | { kind: "step-done"; stepId: number; title: string };

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

export async function* streamMockEvents(): AsyncGenerator<ChatEvent> {
  yield { kind: "message", role: "user", text: "帮我学会梯度下降" };
  await sleep(400);
  yield {
    kind: "message",
    role: "orchestrator",
    text: "收到。我把它拆成 7 步:先建直观,再讲公式与更新法则,然后重点拆解学习率的权衡——这是最常见的误解点。",
  };
  await sleep(600);
  yield {
    kind: "plan",
    title: "教学脚本:梯度下降",
    stepCount: 7,
    stepTitles: [
      "直观:沿山坡下山",
      "损失函数与梯度",
      "更新法则",
      "学习率的影响",
      "收敛轨迹",
      "多维推广",
      "小结与陷阱",
    ],
  };
  await sleep(500);

  const codeStub = (id: number) =>
    `// step ${id} — generated by Animator
const scene = new Scene(container, opts);
const tracker = new ValueTracker(params.lr);
// ... (manim-web scene for step ${id})
await scene.play(new Create(...));`;

  for (let id = 1; id <= 7; id++) {
    const titles = [
      "直观:沿山坡下山",
      "损失函数与梯度",
      "更新法则",
      "学习率的影响",
      "收敛轨迹",
      "多维推广",
      "小结与陷阱",
    ];
    yield { kind: "step-start", stepId: id, title: titles[id - 1] };
    await sleep(450);
    yield { kind: "code-gen", stepId: id, code: codeStub(id) };
    await sleep(500);
    // step 4 故意演示一次纠错
    if (id === 4) {
      yield {
        kind: "verify",
        stepId: id,
        passed: false,
        error: "TypeError: ValueTracker.getValue is not a function (应为 getValue())",
      };
      await sleep(400);
      yield { kind: "code-gen", stepId: id, code: codeStub(id) + "\n// fixed: getValue() API 修正" };
      await sleep(450);
    }
    yield { kind: "verify", stepId: id, passed: true };
    await sleep(250);
    yield { kind: "step-done", stepId: id, title: titles[id - 1] };
    await sleep(300);
  }

  yield {
    kind: "message",
    role: "orchestrator",
    text: '7 步全部生成并通过校验。现在可以在右侧舞台拖动学习率滑块自己探索——试试把 η 拖到 0.9 看看震荡,再追问「步长太大会怎样」。',
  };
}
